### ISSUE TITLE
Why are there 2 different result orders?

### ISSUE THREAD

**Issue by randomJoe211** [vesoft-inc/nebula-graph#587]
![image](https://user-images.githubusercontent.com/69501902/104179060-3f37d680-5446-11eb-94ee-95196bcb40d9.png)

How are they ordered by defaut?

**Comment by yixinglu** [comment]
as far as I know, if you want to get the determinate results, you should limit the sorted rows by ORDER BY.

**Comment by CPWstatic** [comment]
The result is no guarantee of order for now, because the nebula is a distributed system. I will close this issue first util you run into some troubles. And as an alternative way, you could sort the result first if you need an order. And please let us know the details if you truly being troubled with this issue.
